const SELECTED: any[] = [
  {
    "id": "gelato-electronics-1",
    "sku": "GEL-TECH-CASE-GRID",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Tough Case \u2014 Minimal Grid",
    "category": "Accessories",
    "supplierPriceUsd": 8.8,
    "suggestedRetailUsd": 24.9,
    "image": "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80",
    "matchType": "case",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "gelato-electronics-2",
    "sku": "GEL-TECH-CASE-CIRCUIT",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Tough Case \u2014 Circuit Trace",
    "category": "Accessories",
    "supplierPriceUsd": 8.8,
    "suggestedRetailUsd": 25.9,
    "image": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
    "matchType": "case",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "gelato-electronics-3",
    "sku": "GEL-TECH-CASE-PIXEL",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Tough Case \u2014 Nordic Pixel",
    "category": "Accessories",
    "supplierPriceUsd": 8.8,
    "suggestedRetailUsd": 23.9,
    "image": "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?auto=format&fit=crop&w=800&q=80",
    "matchType": "case",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "gelato-electronics-4",
    "sku": "GEL-TECH-CASE-UI",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Tough Case \u2014 Midnight UI",
    "category": "Accessories",
    "supplierPriceUsd": 8.8,
    "suggestedRetailUsd": 26.9,
    "image": "https://images.unsplash.com/photo-1556656793-08538906a9f8?auto=format&fit=crop&w=800&q=80",
    "matchType": "case",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "gelato-electronics-5",
    "sku": "GEL-TECH-TEE-DEBUG",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Debug Mode Unisex Tee",
    "category": "Tech Merch",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 29.9,
    "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "gelato-electronics-6",
    "sku": "GEL-TECH-TEE-SHIP",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Ship It T-Shirt",
    "category": "Tech Merch",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 28.5,
    "image": "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "gelato-electronics-7",
    "sku": "GEL-TECH-TEE-AI",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "AI Ready Soft Tee",
    "category": "Tech Merch",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 27.9,
    "image": "https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "gelato-electronics-8",
    "sku": "GEL-TECH-MUG-ACCENT",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Accent Mug \u2014 Nordic Tech",
    "category": "Tech Merch",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 19.9,
    "image": "https://images.unsplash.com/photo-1514228742587-6b1558fcc036?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "gelato-electronics-9",
    "sku": "GEL-TECH-MUG-COMMIT",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Commit Coffee Mug",
    "category": "Tech Merch",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 18.9,
    "image": "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "gelato-electronics-10",
    "sku": "GEL-TECH-MUG-404",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "404 Not Found Mug",
    "category": "Tech Merch",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 17.9,
    "image": "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "gelato-electronics-11",
    "sku": "GEL-TECH-TEE-LATENCY",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Latency Zero Tee",
    "category": "Tech Merch",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 26.9,
    "image": "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "gelato-electronics-12",
    "sku": "GEL-TECH-CASE-FROST",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Tough Case \u2014 Frost Glass",
    "category": "Accessories",
    "supplierPriceUsd": 8.8,
    "suggestedRetailUsd": 27.5,
    "image": "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?auto=format&fit=crop&w=800&q=80",
    "matchType": "case",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "gelato-electronics-13",
    "sku": "GEL-TECH-CASE-AURORA",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Tough Case \u2014 Aurora Glass",
    "category": "Accessories",
    "supplierPriceUsd": 8.8,
    "suggestedRetailUsd": 28.9,
    "image": "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?auto=format&fit=crop&w=800&q=80",
    "matchType": "case",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "gelato-electronics-14",
    "sku": "GEL-TECH-TEE-COMPILE",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Compile & Ship Tee",
    "category": "Tech Merch",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 27.5,
    "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "gelato-electronics-15",
    "sku": "GEL-TECH-MUG-STACK",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Stack Overflow Mug",
    "category": "Tech Merch",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 18.5,
    "image": "https://images.unsplash.com/photo-1514228742587-6b1558fcc036?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "gelato-electronics-16",
    "sku": "GEL-TECH-CASE-NEON",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Tough Case \u2014 Neon Circuit",
    "category": "Accessories",
    "supplierPriceUsd": 8.8,
    "suggestedRetailUsd": 27.9,
    "image": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
    "matchType": "case",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "gelato-electronics-17",
    "sku": "GEL-TECH-TEE-BINARY",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Binary Dreams Soft Tee",
    "category": "Tech Merch",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 28.5,
    "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "gelato-electronics-18",
    "sku": "GEL-TECH-MUG-ROOT",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Root Access Coffee Mug",
    "category": "Tech Merch",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 19.5,
    "image": "https://images.unsplash.com/photo-1514228742587-6b1558fcc036?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "gelato-electronics-19",
    "sku": "GEL-TECH-CASE-CARBON",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Tough Case \u2014 Carbon Grid",
    "category": "Accessories",
    "supplierPriceUsd": 8.8,
    "suggestedRetailUsd": 26.5,
    "image": "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?auto=format&fit=crop&w=800&q=80",
    "matchType": "case",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "gelato-electronics-20",
    "sku": "GEL-TECH-TEE-DEPLOY",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Deploy Friday Tee",
    "category": "Tech Merch",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 27.9,
    "image": "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "gelato-electronics-21",
    "sku": "GEL-TECH-MUG-NULL",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Null Pointer Mug",
    "category": "Tech Merch",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 17.9,
    "image": "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "gelato-electronics-22",
    "sku": "GEL-TECH-CASE-AURORA2",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Tough Case \u2014 Aurora Code",
    "category": "Accessories",
    "supplierPriceUsd": 8.8,
    "suggestedRetailUsd": 28.9,
    "image": "https://images.unsplash.com/photo-1556656793-08538906a9f8?auto=format&fit=crop&w=800&q=80",
    "matchType": "case",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "gelato-electronics-23",
    "sku": "GEL-TECH-TEE-OSS",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Open Source Soft Tee",
    "category": "Tech Merch",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 26.5,
    "image": "https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "gelato-electronics-24",
    "sku": "GEL-TECH-MUG-KERNEL",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Kernel Panic Mug",
    "category": "Tech Merch",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 18.9,
    "image": "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "gelato-electronics-25",
    "sku": "GEL-TECH-CASE-PIXEL2",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Tough Case \u2014 Pixel Storm",
    "category": "Accessories",
    "supplierPriceUsd": 8.8,
    "suggestedRetailUsd": 29.5,
    "image": "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?auto=format&fit=crop&w=800&q=80",
    "matchType": "case",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "gelato-electronics-26",
    "sku": "GEL-TECH-CASE-MATTE",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Tough Case \u2014 Soft Matte Black",
    "category": "Accessories",
    "supplierPriceUsd": 8.8,
    "suggestedRetailUsd": 26.9,
    "image": "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80",
    "matchType": "case",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "gelato-electronics-27",
    "sku": "GEL-TECH-TEE-COMMIT",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Commit Message Soft Tee",
    "category": "Tech Merch",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 28.5,
    "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "gelato-electronics-28",
    "sku": "GEL-TECH-MUG-OVERFLOW",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Coffee Overflow Mug",
    "category": "Tech Merch",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 18.5,
    "image": "https://images.unsplash.com/photo-1514228742587-6b1558fcc036?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "gelato-electronics-29",
    "sku": "GEL-TECH-CASE-BLUE",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Tough Case \u2014 Blueprint Lines",
    "category": "Accessories",
    "supplierPriceUsd": 8.8,
    "suggestedRetailUsd": 27.5,
    "image": "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80",
    "matchType": "case",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "gelato-electronics-30",
    "sku": "GEL-TECH-TEE-SHIP2",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Ship Clean Soft Tee",
    "category": "Tech Merch",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 27.5,
    "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "gelato-electronics-31",
    "sku": "GEL-TECH-MUG-LATENCY",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Latency Low Mug",
    "category": "Tech Merch",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 17.5,
    "image": "https://images.unsplash.com/photo-1514228742587-6b1558fcc036?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "gelato-electronics-32",
    "sku": "GEL-TECH-CASE-GRAD",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Tough Case \u2014 Soft Gradient",
    "category": "Accessories",
    "supplierPriceUsd": 8.8,
    "suggestedRetailUsd": 28.5,
    "image": "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80",
    "matchType": "case",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "gelato-electronics-33",
    "sku": "GEL-TECH-TEE-DOCS",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Read The Docs Soft Tee",
    "category": "Tech Merch",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 26.5,
    "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "gelato-electronics-34",
    "sku": "GEL-TECH-MUG-SUDO",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Sudo Coffee Mug",
    "category": "Tech Merch",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 19.5,
    "image": "https://images.unsplash.com/photo-1514228742587-6b1558fcc036?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "gelato-electronics-35",
    "sku": "GEL-TECH-CASE-TERM",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Tough Case \u2014 Terminal Green",
    "category": "Accessories",
    "supplierPriceUsd": 8.8,
    "suggestedRetailUsd": 29.5,
    "image": "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80",
    "matchType": "case",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "gelato-electronics-36",
    "sku": "GEL-TECH-TEE-MERGE",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Merge Ready Soft Tee",
    "category": "Tech Merch",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 29.5,
    "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "gelato-electronics-37",
    "sku": "GEL-TECH-MUG-HELLO",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Hello World Mug",
    "category": "Tech Merch",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 16.5,
    "image": "https://images.unsplash.com/photo-1514228742587-6b1558fcc036?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "gelato-electronics-38",
    "sku": "GEL-TECH-CASE-NIGHT",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Tough Case \u2014 Nordic Night",
    "category": "Accessories",
    "supplierPriceUsd": 8.8,
    "suggestedRetailUsd": 27.9,
    "image": "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80",
    "matchType": "case",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "gelato-electronics-39",
    "sku": "GEL-TECH-TEE-API",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "API First Soft Tee",
    "category": "Tech Merch",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 28.9,
    "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "gelato-electronics-40",
    "sku": "GEL-TECH-MUG-CACHE",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Cache Hit Coffee Mug",
    "category": "Tech Merch",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 18.9,
    "image": "https://images.unsplash.com/photo-1514228742587-6b1558fcc036?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "gelato-electronics-41",
    "sku": "GEL-TECH-CASE-SPECKLE",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Tough Case \u2014 Soft Speckle",
    "category": "Accessories",
    "supplierPriceUsd": 8.8,
    "suggestedRetailUsd": 26.5,
    "image": "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80",
    "matchType": "case",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "gelato-electronics-42",
    "sku": "GEL-TECH-TEE-OFFLINE",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Offline Mode Soft Tee",
    "category": "Tech Merch",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 25.5,
    "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "gelato-electronics-43",
    "sku": "GEL-TECH-MUG-PING",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Ping Ok Mug",
    "category": "Tech Merch",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 17.9,
    "image": "https://images.unsplash.com/photo-1514228742587-6b1558fcc036?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "gelato-electronics-44",
    "sku": "GEL-TECH-CASE-WIRE",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Tough Case \u2014 Wireframe Soft",
    "category": "Accessories",
    "supplierPriceUsd": 8.8,
    "suggestedRetailUsd": 28.9,
    "image": "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80",
    "matchType": "case",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "gelato-electronics-45",
    "sku": "GEL-TECH-TEE-BUILD",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Build Once Soft Tee",
    "category": "Tech Merch",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 27.9,
    "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "gelato-electronics-46",
    "sku": "GEL-TECH-MUG-DARK",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Dark Mode Coffee Mug",
    "category": "Tech Merch",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 19.9,
    "image": "https://images.unsplash.com/photo-1514228742587-6b1558fcc036?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "gelato-electronics-47",
    "sku": "GEL-TECH-CASE-CLOUD",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Tough Case \u2014 Soft Cloud",
    "category": "Accessories",
    "supplierPriceUsd": 8.8,
    "suggestedRetailUsd": 25.9,
    "image": "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80",
    "matchType": "case",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "gelato-electronics-48",
    "sku": "GEL-TECH-TEE-SYNTAX",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Syntax Soft Tee",
    "category": "Tech Merch",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 26.9,
    "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "gelato-electronics-49",
    "sku": "GEL-TECH-MUG-UPTIME",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Uptime Club Mug",
    "category": "Tech Merch",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 18.5,
    "image": "https://images.unsplash.com/photo-1514228742587-6b1558fcc036?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "gelato-electronics-50",
    "sku": "GEL-TECH-CASE-MONO",
    "supplier": "Gelato",
    "provider": "gelato",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Tough Case \u2014 Soft Mono",
    "category": "Accessories",
    "supplierPriceUsd": 8.8,
    "suggestedRetailUsd": 29.9,
    "image": "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80",
    "matchType": "case",
    "sector": "electronics",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  }
];
const SECTOR_ALIASES: Record<string, string> = {
  "beauty": "beauty",
  "perfume": "beauty",
  "perfumes": "beauty",
  "skincare": "beauty",
  "toys": "toys",
  "kids": "toys",
  "kid": "toys",
  "children": "toys",
  "electronics": "electronics",
  "tech": "electronics",
  "technology": "electronics",
  "pet supplies": "pet supplies",
  "pets": "pet supplies",
  "pet": "pet supplies",
  "home living": "home living",
  "home": "home living",
  "living": "home living",
  "fitness": "fitness",
  "outdoor": "fitness",
  "sports": "fitness",
  "solar energy": "solar energy",
  "energy": "solar energy",
  "solar": "solar energy",
  "car accessories": "car accessories",
  "car": "car accessories",
  "auto": "car accessories",
  "automotive": "car accessories"
};
function money(value: unknown) {
  const amount = Number(value);
  return Number.isFinite(amount) && amount > 0 ? Math.round(amount * 100) / 100 : 0;
}
function resolveSector(raw: string) {
  const key = String(raw || "").toLowerCase().trim();
  if (!key) return SELECTED[0]?.sector || "beauty";
  if (SECTOR_ALIASES[key]) return SECTOR_ALIASES[key];
  for (const [alias, sector] of Object.entries(SECTOR_ALIASES)) {
    if (key.includes(alias) || alias.includes(key)) return sector;
  }
  return key;
}
function curated(sector: string) {
  return SELECTED
    .filter((p) => !p.sector || String(p.sector).toLowerCase() === sector)
    .map((p, i) => ({
      id: String(p.id || `gelato-selected-${i}`),
      sku: String(p.sku || ""),
      supplier: "Gelato",
      provider: "gelato",
      name: String(p.name || "Gelato product"),
      category: String(p.category || sector),
      supplierPriceUsd: money(p.supplierPriceUsd) || money(p.suggestedRetailUsd),
      suggestedRetailUsd: money(p.suggestedRetailUsd) || money(p.supplierPriceUsd),
      image: String(p.image || ""),
      sector: String(p.sector || sector),
    }))
    .filter((p) => p.suggestedRetailUsd > 0 && p.name);
}
export default async (req: Request, context: any) => {
  if (req.method !== "GET") return Response.json({ error: "Method not allowed" }, { status: 405 });
  const url = new URL(req.url);
  const wanted = url.searchParams.get("q") || url.searchParams.get("sector") || "";
  const defaultSector = String(SELECTED[0]?.sector || "beauty");
  const sector = resolveSector(wanted || defaultSector);
  const headers = { "access-control-allow-origin": "*", "cache-control": "public, max-age=60" };
  const products = curated(sector).slice(0, 50);
  return Response.json(
    { ok: true, supplier: "gelato", sector, query: sector, products, count: products.length, source: "gelato-selected-primary", markets: ["NO", "EU", "PE"] },
    { status: products.length ? 200 : 503, headers }
  );
};
export const config = { path: "/api/gelato-products" };
