const SELECTED: any[] = [
  {
    "id": "printful-electronics-1",
    "sku": "PFL-TECH-CASE-GRID",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Tough Case \u2014 Minimal Grid",
    "category": "Accessories",
    "supplierPriceUsd": 8.8,
    "suggestedRetailUsd": 24.9,
    "image": "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80",
    "matchType": "case",
    "sector": "electronics"
  },
  {
    "id": "printful-electronics-2",
    "sku": "PFL-TECH-CASE-CIRCUIT",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Tough Case \u2014 Circuit Trace",
    "category": "Accessories",
    "supplierPriceUsd": 8.8,
    "suggestedRetailUsd": 25.9,
    "image": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
    "matchType": "case",
    "sector": "electronics"
  },
  {
    "id": "printful-electronics-3",
    "sku": "PFL-TECH-CASE-PIXEL",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Tough Case \u2014 Nordic Pixel",
    "category": "Accessories",
    "supplierPriceUsd": 8.8,
    "suggestedRetailUsd": 23.9,
    "image": "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?auto=format&fit=crop&w=800&q=80",
    "matchType": "case",
    "sector": "electronics"
  },
  {
    "id": "printful-electronics-4",
    "sku": "PFL-TECH-CASE-UI",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Tough Case \u2014 Midnight UI",
    "category": "Accessories",
    "supplierPriceUsd": 8.8,
    "suggestedRetailUsd": 26.9,
    "image": "https://images.unsplash.com/photo-1556656793-08538906a9f8?auto=format&fit=crop&w=800&q=80",
    "matchType": "case",
    "sector": "electronics"
  },
  {
    "id": "printful-electronics-5",
    "sku": "PFL-TECH-TEE-DEBUG",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Debug Mode Unisex Tee",
    "category": "Tech Merch",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 29.9,
    "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "electronics"
  },
  {
    "id": "printful-electronics-6",
    "sku": "PFL-TECH-TEE-SHIP",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Ship It T-Shirt",
    "category": "Tech Merch",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 28.5,
    "image": "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "electronics"
  },
  {
    "id": "printful-electronics-7",
    "sku": "PFL-TECH-TEE-AI",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "AI Ready Soft Tee",
    "category": "Tech Merch",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 27.9,
    "image": "https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "electronics"
  },
  {
    "id": "printful-electronics-8",
    "sku": "PFL-TECH-MUG-ACCENT",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Accent Mug \u2014 Nordic Tech",
    "category": "Tech Merch",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 19.9,
    "image": "https://images.unsplash.com/photo-1514228742587-6b1558fcc036?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "electronics"
  },
  {
    "id": "printful-electronics-9",
    "sku": "PFL-TECH-MUG-COMMIT",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Commit Coffee Mug",
    "category": "Tech Merch",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 18.9,
    "image": "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "electronics"
  },
  {
    "id": "printful-electronics-10",
    "sku": "PFL-TECH-MUG-404",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "404 Not Found Mug",
    "category": "Tech Merch",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 17.9,
    "image": "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "electronics"
  },
  {
    "id": "printful-electronics-11",
    "sku": "PFL-TECH-TEE-LATENCY",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Latency Zero Tee",
    "category": "Tech Merch",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 26.9,
    "image": "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "electronics"
  },
  {
    "id": "printful-electronics-12",
    "sku": "PFL-TECH-CASE-FROST",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Tough Case \u2014 Frost Glass",
    "category": "Accessories",
    "supplierPriceUsd": 8.8,
    "suggestedRetailUsd": 27.5,
    "image": "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?auto=format&fit=crop&w=800&q=80",
    "matchType": "case",
    "sector": "electronics"
  },
  {
    "id": "printful-electronics-13",
    "sku": "PFL-TECH-CASE-AURORA",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Tough Case \u2014 Aurora Glass",
    "category": "Accessories",
    "supplierPriceUsd": 8.8,
    "suggestedRetailUsd": 28.9,
    "image": "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?auto=format&fit=crop&w=800&q=80",
    "matchType": "case",
    "sector": "electronics"
  },
  {
    "id": "printful-electronics-14",
    "sku": "PFL-TECH-TEE-COMPILE",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Compile & Ship Tee",
    "category": "Tech Merch",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 27.5,
    "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "electronics"
  },
  {
    "id": "printful-electronics-15",
    "sku": "PFL-TECH-MUG-STACK",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Stack Overflow Mug",
    "category": "Tech Merch",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 18.5,
    "image": "https://images.unsplash.com/photo-1514228742587-6b1558fcc036?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "electronics"
  },
  {
    "id": "printful-electronics-16",
    "sku": "PFL-TECH-CASE-NEON",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Tough Case \u2014 Neon Circuit",
    "category": "Accessories",
    "supplierPriceUsd": 8.8,
    "suggestedRetailUsd": 27.9,
    "image": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
    "matchType": "case",
    "sector": "electronics"
  },
  {
    "id": "printful-electronics-17",
    "sku": "PFL-TECH-TEE-BINARY",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Binary Dreams Soft Tee",
    "category": "Tech Merch",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 28.5,
    "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "electronics"
  },
  {
    "id": "printful-electronics-18",
    "sku": "PFL-TECH-MUG-ROOT",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Root Access Coffee Mug",
    "category": "Tech Merch",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 19.5,
    "image": "https://images.unsplash.com/photo-1514228742587-6b1558fcc036?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "electronics"
  },
  {
    "id": "printful-electronics-19",
    "sku": "PFL-TECH-CASE-CARBON",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Tough Case \u2014 Carbon Grid",
    "category": "Accessories",
    "supplierPriceUsd": 8.8,
    "suggestedRetailUsd": 26.5,
    "image": "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?auto=format&fit=crop&w=800&q=80",
    "matchType": "case",
    "sector": "electronics"
  },
  {
    "id": "printful-electronics-20",
    "sku": "PFL-TECH-TEE-DEPLOY",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Deploy Friday Tee",
    "category": "Tech Merch",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 27.9,
    "image": "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "electronics"
  },
  {
    "id": "printful-electronics-21",
    "sku": "PFL-TECH-MUG-NULL",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Null Pointer Mug",
    "category": "Tech Merch",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 17.9,
    "image": "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "electronics"
  },
  {
    "id": "printful-electronics-22",
    "sku": "PFL-TECH-CASE-AURORA2",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Tough Case \u2014 Aurora Code",
    "category": "Accessories",
    "supplierPriceUsd": 8.8,
    "suggestedRetailUsd": 28.9,
    "image": "https://images.unsplash.com/photo-1556656793-08538906a9f8?auto=format&fit=crop&w=800&q=80",
    "matchType": "case",
    "sector": "electronics"
  },
  {
    "id": "printful-electronics-23",
    "sku": "PFL-TECH-TEE-OSS",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Open Source Soft Tee",
    "category": "Tech Merch",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 26.5,
    "image": "https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "electronics"
  },
  {
    "id": "printful-electronics-24",
    "sku": "PFL-TECH-MUG-KERNEL",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Kernel Panic Mug",
    "category": "Tech Merch",
    "supplierPriceUsd": 6.5,
    "suggestedRetailUsd": 18.9,
    "image": "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80",
    "matchType": "mug",
    "sector": "electronics"
  },
  {
    "id": "printful-electronics-25",
    "sku": "PFL-TECH-CASE-PIXEL2",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Tough Case \u2014 Pixel Storm",
    "category": "Accessories",
    "supplierPriceUsd": 8.8,
    "suggestedRetailUsd": 29.5,
    "image": "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?auto=format&fit=crop&w=800&q=80",
    "matchType": "case",
    "sector": "electronics"
  }
];
const SECTOR_ALIASES: Record<string, string> = {
  "beauty": "beauty",
  "perfume": "beauty",
  "perfumes": "beauty",
  "skincare": "beauty",
  "toys": "toys",
  "kids": "toys",
  "kid": "toys",
  "children": "toys",
  "electronics": "electronics",
  "tech": "electronics",
  "technology": "electronics",
  "pet supplies": "pet supplies",
  "pets": "pet supplies",
  "pet": "pet supplies",
  "home living": "home living",
  "home": "home living",
  "living": "home living",
  "fitness": "fitness",
  "outdoor": "fitness",
  "sports": "fitness",
  "solar energy": "solar energy",
  "energy": "solar energy",
  "solar": "solar energy",
  "car accessories": "car accessories",
  "car": "car accessories",
  "auto": "car accessories",
  "automotive": "car accessories"
};
function money(value: unknown) {
  const amount = Number(value);
  return Number.isFinite(amount) && amount > 0 ? Math.round(amount * 100) / 100 : 0;
}
function resolveSector(raw: string) {
  const key = String(raw || "").toLowerCase().trim();
  if (!key) return SELECTED[0]?.sector || "beauty";
  if (SECTOR_ALIASES[key]) return SECTOR_ALIASES[key];
  for (const [alias, sector] of Object.entries(SECTOR_ALIASES)) {
    if (key.includes(alias) || alias.includes(key)) return sector;
  }
  return key;
}
function curated(sector: string) {
  return SELECTED
    .filter((p) => !p.sector || String(p.sector).toLowerCase() === sector)
    .map((p, i) => ({
      id: String(p.id || `printful-selected-${i}`),
      sku: String(p.sku || ""),
      supplier: "Printful",
      provider: "printful",
      name: String(p.name || "Printful product"),
      category: String(p.category || sector),
      supplierPriceUsd: money(p.supplierPriceUsd) || money(p.suggestedRetailUsd),
      suggestedRetailUsd: money(p.suggestedRetailUsd) || money(p.supplierPriceUsd),
      image: String(p.image || ""),
      sector: String(p.sector || sector),
    }))
    .filter((p) => p.suggestedRetailUsd > 0 && p.name);
}
export default async (req: Request, context: any) => {
  if (req.method !== "GET") return Response.json({ error: "Method not allowed" }, { status: 405 });
  const url = new URL(req.url);
  const wanted = url.searchParams.get("q") || url.searchParams.get("sector") || "";
  const defaultSector = String(SELECTED[0]?.sector || "beauty");
  const sector = resolveSector(wanted || defaultSector);
  const headers = { "access-control-allow-origin": "*", "cache-control": "public, max-age=60" };
  const products = curated(sector).slice(0, 30);
  return Response.json(
    { ok: true, supplier: "printful", sector, query: sector, products, count: products.length, source: "printful-selected-primary", markets: ["NO", "EU", "PE"] },
    { status: products.length ? 200 : 503, headers }
  );
};
export const config = { path: "/api/printful-products" };
