import { withQuotes } from "../_shared/quote";
import LINKED from "../../catalog/printify-selected.json";

/**
 * Printify catalog = ONLY real products that exist in Printify shop 28847802 ("Printify ML").
 * Every row carries the real Printify product_id + variant_id (validated with the Printify
 * shipping calculator to a Norwegian address), so Checkout -> webhook -> Make can submit the
 * order automatically. There is no type-word matching any more: a row is sold only if it is linked.
 * Rows are generated by /workspace/pfy/build_catalog.py; prices are NOK-based (retailNok / 11.3 = USD basis).
 */
export const PRINTIFY_SHOP_ID = "28847802";
const PRODUCT_ID = /^[0-9a-f]{24}$/;
const VARIANT_ID = /^\d+$/;

function money(value: unknown) {
  const amount = Number(value);
  return Number.isFinite(amount) && amount > 0 ? Math.round(amount * 100) / 100 : 0;
}

export function linkedProducts(rows: unknown = LINKED) {
  const list = Array.isArray(rows) ? rows : [];
  return list
    .filter((p: any) => p && PRODUCT_ID.test(String(p.printifyProductId || "")) && VARIANT_ID.test(String(p.printifyVariantId || "")))
    .map((p: any) => ({
      id: String(p.id),
      sku: String(p.sku || ""),
      supplier: "Printify",
      provider: "printify",
      printifyProductId: String(p.printifyProductId),
      printifyVariantId: String(p.printifyVariantId),
      printifyMatch: "id",
      name: String(p.name || "Printify product"),
      size: String(p.size || ""),
      category: String(p.category || ""),
      description: String(p.description || ""),
      supplierPriceUsd: money(p.supplierPriceUsd),
      suggestedRetailUsd: money(p.suggestedRetailUsd),
      retailNok: Number(p.retailNok) || 0,
      image: String(p.image || ""),
      images: Array.isArray(p.images) ? p.images.map(String) : [],
      matchType: String(p.matchType || ""),
      sector: String(p.sector || ""),
      printProvider: String(p.printProvider || ""),
      origin: String(p.origin || ""),
      compliance: String(p.compliance || "EU/Nordic POD merch"),
    }))
    .filter((p) => p.suggestedRetailUsd > 0 && p.name);
}

export async function onRequestGet(context: any) {
  const url = new URL(context.request.url);
  const query = url.searchParams.get("q") || url.searchParams.get("sector") || "";
  const headers = { "access-control-allow-origin": "*", "cache-control": "public, max-age=60" };
  let products: any[] = linkedProducts();
  products = await withQuotes(
    context.env,
    "printify",
    products,
    (p: any) => ({ printify_product_id: p.printifyProductId, printify_variant_id: p.printifyVariantId }),
    () => "id",
  );
  const sector = products[0]?.sector || "";
  return Response.json(
    { ok: true, supplier: "printify", sector, query: query || sector, products, count: products.length, source: "printify-shop-linked", shopId: PRINTIFY_SHOP_ID, compliance: "EU/Nordic POD merch (EU print providers)", markets: ["NO", "EU", "PE"] },
    { status: products.length ? 200 : 503, headers },
  );
}
